-- Migration 032: Payment Batches
-- Combines multiple vouchers (same payee + payment mode) into a single bank transfer.
-- Reference format: CPAY-{FY}-{00001}
--
-- Prerequisites confirmed (Query 1 investigation):
--   - vouchers.payee_id is a normalized FK (UUID) — payee_id equality = same destination
--   - vouchers.payment_mode CHECK('UPI','Account Transfer','Cash')
--   - No separate destination_account_id exists; payee_id + payment_mode is the unique key
--   - Eligible voucher statuses for batching: 'awaiting_payment' OR 'completed'
--     (mark-paid already accepts both; batch mark-paid mirrors this)
--   - paid_from_account on vouchers is free text (no FK); source account is NOT enforced here
--   - Vouchers are IMMUTABLE after 'draft': PUT /api/vouchers/:id rejects status != 'draft'.
--     Therefore payee_id/payment_mode cannot change after a voucher enters a batch.
--     The insert-time trigger is the only enforcement needed; no UPDATE trigger is required.
--   - RLS USING(true): consistent with every other table in this project — real access control
--     lives in Express role-check middleware, not Postgres RLS.
--
-- Atomicity note (Query 2 investigation):
--   combine-settlements is application-layer only with no Postgres transaction.
--   The batch_mark_paid RPC below IS a proper Postgres transaction, fixing that gap.
--
-- 'partially_reversed' status is reserved for a future phase (individual voucher reversal
-- within a paid batch). Nothing in this migration or Query 4 implements the transition into
-- that state — it is included in the CHECK constraint now to avoid an ALTER TABLE later.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. payment_batch_series — sequence counter for CPAY references, one row per company
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS payment_batch_series (
  company_id TEXT PRIMARY KEY REFERENCES companies(id),
  current_number INTEGER NOT NULL DEFAULT 0,
  financial_year TEXT
);
INSERT INTO payment_batch_series (company_id, current_number, financial_year)
  SELECT id, 0, '2026-27' FROM companies
  ON CONFLICT (company_id) DO NOTHING;

ALTER TABLE payment_batch_series ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all operations for service role"
  ON payment_batch_series FOR ALL USING (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. RPC: get_next_batch_reference
--    Uses SELECT ... FOR UPDATE + separate UPDATE (same row-locking idiom as
--    get_next_voucher_number) rather than INSERT ... ON CONFLICT.
--    Functionally equivalent; comment previously said "mirrors exactly" — corrected.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION get_next_batch_reference(p_company_id TEXT)
RETURNS TEXT AS $$
DECLARE
  v_series      RECORD;
  v_next_number INTEGER;
  v_current_fy  TEXT;
  v_ref         TEXT;
BEGIN
  v_current_fy := CASE
    WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4
    THEN EXTRACT(YEAR FROM CURRENT_DATE)::TEXT
         || '-'
         || LPAD(((EXTRACT(YEAR FROM CURRENT_DATE)::INT + 1) % 100)::TEXT, 2, '0')
    ELSE (EXTRACT(YEAR FROM CURRENT_DATE)::INT - 1)::TEXT
         || '-'
         || LPAD((EXTRACT(YEAR FROM CURRENT_DATE)::INT % 100)::TEXT, 2, '0')
  END;

  SELECT * INTO v_series FROM payment_batch_series
    WHERE company_id = p_company_id FOR UPDATE;

  v_next_number := v_series.current_number + 1;

  UPDATE payment_batch_series
    SET current_number = v_next_number, financial_year = v_current_fy
    WHERE company_id = p_company_id;

  -- Format: CPAY-2026-27-00001
  v_ref := 'CPAY-' || v_current_fy || '-' || LPAD(v_next_number::TEXT, 5, '0');
  RETURN v_ref;
END;
$$ LANGUAGE plpgsql;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. payment_batches — one row per combined payment
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS payment_batches (
  id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id        TEXT NOT NULL REFERENCES companies(id),
  batch_reference   TEXT NOT NULL,            -- CPAY-2026-27-00001 (generated by RPC)

  -- Grouping key: every voucher in this batch must share BOTH of these values.
  -- payee_id owns the destination account info (bank_account / upi_id / ifsc).
  -- payment_mode determines which account field is used.
  -- Together they uniquely identify the destination — no separate account FK needed.
  -- Vouchers are immutable post-draft, so these values cannot drift after batch creation.
  payee_id          UUID NOT NULL REFERENCES payees(id),
  payment_mode      TEXT NOT NULL CHECK(payment_mode IN ('UPI', 'Account Transfer')),
  -- Cash is excluded: combining cash payments into a single transfer is nonsensical.

  total_amount      DECIMAL(15,2) NOT NULL,

  status            TEXT NOT NULL DEFAULT 'pending'
                    CHECK(status IN (
                      'pending',
                      'paid',
                      'cancelled',          -- dissolved before payment; vouchers released
                      'partially_reversed'  -- reserved for future phase; not yet implemented
                    )),

  -- Set when the batch is marked paid
  payment_reference TEXT,                     -- UTR / UPI transaction ID
  payment_notes     TEXT,
  payment_receipt_url TEXT,
  paid_by           UUID REFERENCES users(id),
  paid_at           TIMESTAMPTZ,

  -- Set when the batch is cancelled
  cancelled_by      UUID REFERENCES users(id),
  cancelled_at      TIMESTAMPTZ,
  cancellation_reason TEXT,

  -- Audit
  created_by        UUID NOT NULL REFERENCES users(id),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE(company_id, batch_reference)
);

CREATE INDEX IF NOT EXISTS idx_payment_batches_company_status
  ON payment_batches (company_id, status);
CREATE INDEX IF NOT EXISTS idx_payment_batches_payee
  ON payment_batches (payee_id);
CREATE INDEX IF NOT EXISTS idx_payment_batches_reference
  ON payment_batches (batch_reference);

ALTER TABLE payment_batches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all operations for service role"
  ON payment_batches FOR ALL USING (true);

COMMENT ON COLUMN payment_batches.payee_id
  IS 'All vouchers in this batch must share this payee_id — enforced by trigger on payment_batch_vouchers.';
COMMENT ON COLUMN payment_batches.payment_mode
  IS 'All vouchers must share this payment_mode — enforced by trigger. Cash excluded at CHECK level.';
COMMENT ON COLUMN payment_batches.status
  IS 'partially_reversed is reserved for a future reversal phase and is not yet transitioned into by any RPC.';

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. payment_batch_vouchers — join table
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS payment_batch_vouchers (
  batch_id    UUID NOT NULL REFERENCES payment_batches(id) ON DELETE CASCADE,
  voucher_id  UUID NOT NULL REFERENCES vouchers(id),
  PRIMARY KEY (batch_id, voucher_id),
  UNIQUE (voucher_id)  -- a voucher can only be in ONE active batch at a time
);

ALTER TABLE payment_batch_vouchers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all operations for service role"
  ON payment_batch_vouchers FOR ALL USING (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. Hard DB-level constraint trigger (INSERT only — no UPDATE trigger needed
--    because vouchers are immutable post-draft; payee_id/payment_mode cannot
--    change after a voucher reaches awaiting_payment/completed status).
--
--    Every voucher inserted into payment_batch_vouchers MUST:
--      a) Have status IN ('awaiting_payment', 'completed') — payable, not yet paid
--      b) Have payee_id  = the batch's payee_id   (same destination)
--      c) Have payment_mode = the batch's payment_mode (same channel)
--
--    Violation raises an exception that rolls back the INSERT — not a soft warning,
--    not an app-layer check. No override, no admin bypass.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION check_batch_voucher_compatibility()
RETURNS TRIGGER AS $$
DECLARE
  v_batch   RECORD;
  v_voucher RECORD;
BEGIN
  SELECT payee_id, payment_mode, status AS batch_status INTO v_batch
    FROM payment_batches WHERE id = NEW.batch_id;

  -- Do not allow vouchers to be added to a cancelled or paid batch
  IF v_batch.batch_status NOT IN ('pending') THEN
    RAISE EXCEPTION
      'Cannot add vouchers to a batch that is already % — only pending batches accept new vouchers.',
      v_batch.batch_status;
  END IF;

  SELECT payee_id, payment_mode, status, serial_number INTO v_voucher
    FROM vouchers WHERE id = NEW.voucher_id;

  -- (a) Status check: must be payable
  IF v_voucher.status NOT IN ('awaiting_payment', 'completed') THEN
    RAISE EXCEPTION
      'Voucher % (status: %) cannot be added to a payment batch — only awaiting_payment or completed vouchers are eligible.',
      v_voucher.serial_number, v_voucher.status;
  END IF;

  -- (b) Payee must match batch payee exactly
  IF v_voucher.payee_id <> v_batch.payee_id THEN
    RAISE EXCEPTION
      'Voucher % has a different payee from this batch. Same-payee is mandatory — vouchers with different payees must be separate payments.',
      v_voucher.serial_number;
  END IF;

  -- (c) Payment mode must match exactly
  IF v_voucher.payment_mode <> v_batch.payment_mode THEN
    RAISE EXCEPTION
      'Voucher % uses payment_mode "%" but this batch requires "%". Same payment mode is mandatory — vouchers with different modes must be separate payments.',
      v_voucher.serial_number, v_voucher.payment_mode, v_batch.payment_mode;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER enforce_batch_voucher_compatibility
  BEFORE INSERT ON payment_batch_vouchers
  FOR EACH ROW EXECUTE FUNCTION check_batch_voucher_compatibility();

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. cancel_payment_batch RPC
--
--    Dissolves a pending batch and releases its vouchers back to unbatched status.
--    Uses ON DELETE CASCADE on payment_batch_vouchers.batch_id, so deleting the
--    join rows is automatic. The batch row itself is kept with status='cancelled'
--    for audit trail.
--
--    Required because UNIQUE(voucher_id) on payment_batch_vouchers means a voucher
--    in a pending batch cannot be batched elsewhere — without cancellation, a batch
--    whose batch_mark_paid raises an exception (e.g. one voucher paid externally)
--    would permanently lock all its other vouchers.
--
--    NOTIFICATION: this RPC does NOT send a notification to the batch creator.
--    Notifications are handled at the Express route layer (POST /api/batches/:id/cancel)
--    following the same pattern as every other state-transition endpoint in this app
--    (approve, reject, dequeue, etc.). The route must notify created_by after calling
--    this RPC. Scoped to Query 4.
--
--    KNOWN TIMING GAP (low priority, no fix needed for this volume):
--    The FOR UPDATE lock here protects against concurrent cancellation of the SAME
--    batch, but does not lock the individual voucher rows. A simultaneous
--    "cancel batch" + "mark this voucher paid individually" pair of requests could
--    theoretically interleave. Given this is a low-concurrency internal tool with a
--    small accounts team, this is acceptable. If throughput ever increases, add
--    SELECT ... FOR UPDATE on the voucher rows inside both cancel_payment_batch and
--    the reciprocal guard in mark-paid.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION cancel_payment_batch(
  p_batch_id          UUID,
  p_cancelled_by      UUID,
  p_reason            TEXT DEFAULT NULL
)
RETURNS JSONB AS $$
DECLARE
  v_batch         RECORD;
  v_voucher_count INTEGER;
BEGIN
  SELECT * INTO v_batch FROM payment_batches
    WHERE id = p_batch_id FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Payment batch % not found', p_batch_id;
  END IF;

  IF v_batch.status <> 'pending' THEN
    RAISE EXCEPTION 'Only pending batches can be cancelled (batch % is %)',
      v_batch.batch_reference, v_batch.status;
  END IF;

  -- Count vouchers before cascade-deleting them (for the return value)
  SELECT COUNT(*) INTO v_voucher_count
    FROM payment_batch_vouchers WHERE batch_id = p_batch_id;

  -- Release vouchers: ON DELETE CASCADE on payment_batch_vouchers.batch_id handles the join rows.
  -- Vouchers themselves are not touched — their status remains unchanged; they simply become
  -- unbatched and eligible to be added to a new batch or paid individually.
  DELETE FROM payment_batch_vouchers WHERE batch_id = p_batch_id;

  -- Mark batch cancelled (retain for audit; do not delete the batch row)
  UPDATE payment_batches SET
    status             = 'cancelled',
    cancelled_by       = p_cancelled_by,
    cancelled_at       = NOW(),
    cancellation_reason = p_reason
  WHERE id = p_batch_id;

  RETURN jsonb_build_object(
    'success',           true,
    'batch_reference',   v_batch.batch_reference,
    'vouchers_released', v_voucher_count
  );
END;
$$ LANGUAGE plpgsql;

-- ─────────────────────────────────────────────────────────────────────────────
-- 7. batch_mark_paid RPC — atomic multi-voucher transition.
--    Wraps all updates in ONE Postgres transaction, fixing the partial-commit gap
--    found in combine-settlements (which uses concurrent Promise.all with no rollback).
--
--    Reciprocal guard against single-voucher mark-paid bypassing a batch:
--    The single-voucher /api/vouchers/:id/mark-paid endpoint must check
--    payment_batch_vouchers BEFORE proceeding — this is enforced in app code
--    (server-supabase.js) not here, since SQL triggers cannot block HTTP calls.
--    See the guard added in server-supabase.js alongside this migration.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION batch_mark_paid(
  p_batch_id          UUID,
  p_paid_by           UUID,
  p_payment_reference TEXT DEFAULT NULL,
  p_payment_notes     TEXT DEFAULT NULL,
  p_receipt_url       TEXT DEFAULT NULL
)
RETURNS JSONB AS $$
DECLARE
  v_batch       RECORD;
  v_now         TIMESTAMPTZ := NOW();
  v_voucher_ids UUID[];
  v_count       INTEGER;
BEGIN
  -- Lock the batch row to prevent concurrent mark-paid on the same batch
  SELECT * INTO v_batch FROM payment_batches
    WHERE id = p_batch_id FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Payment batch % not found', p_batch_id;
  END IF;

  IF v_batch.status <> 'pending' THEN
    RAISE EXCEPTION 'Batch % is already % — cannot mark paid again',
      v_batch.batch_reference, v_batch.status;
  END IF;

  -- Count all vouchers in the batch
  SELECT COUNT(*) INTO v_count
    FROM payment_batch_vouchers WHERE batch_id = p_batch_id;

  -- Collect only the vouchers that are STILL in a payable state
  SELECT ARRAY_AGG(v.id) INTO v_voucher_ids
    FROM payment_batch_vouchers bv
    JOIN vouchers v ON v.id = bv.voucher_id
    WHERE bv.batch_id = p_batch_id
      AND v.status IN ('awaiting_payment', 'completed');

  -- If any voucher is no longer payable, reject the entire batch mark-paid.
  -- Caller should cancel the batch (via cancel_payment_batch) to release
  -- the remaining vouchers if this error is unrecoverable.
  IF COALESCE(ARRAY_LENGTH(v_voucher_ids, 1), 0) <> v_count THEN
    RAISE EXCEPTION
      'One or more vouchers in batch % are no longer in a payable state (status not in awaiting_payment/completed). '
      'Use cancel_payment_batch(''%'') to release the remaining vouchers, then handle each individually.',
      v_batch.batch_reference, p_batch_id;
  END IF;

  -- Transition all vouchers to paid atomically
  UPDATE vouchers SET
    status              = 'paid',
    payment_reference   = p_payment_reference,
    payment_notes       = p_payment_notes,
    payment_receipt_url = p_receipt_url,
    paid_by             = p_paid_by,
    paid_at             = v_now
  WHERE id = ANY(v_voucher_ids);

  -- Mark the batch itself as paid
  UPDATE payment_batches SET
    status              = 'paid',
    payment_reference   = p_payment_reference,
    payment_notes       = p_payment_notes,
    payment_receipt_url = p_receipt_url,
    paid_by             = p_paid_by,
    paid_at             = v_now
  WHERE id = p_batch_id;

  RETURN jsonb_build_object(
    'success',        true,
    'batch_reference', v_batch.batch_reference,
    'vouchers_paid',  ARRAY_LENGTH(v_voucher_ids, 1)
  );
END;
$$ LANGUAGE plpgsql;
